### ISSUE TITLE
Make polymer_ui_elements usable for SDK is 1.0.0+3.r30188 or higer.

### ISSUE THREAD

**Issue by a4snet** [bwu-dart-graveyard/polymer_ui_elements#66]
--- 08.12.2013 22:38:00 Running pub get ... ---
Pub get failed, [1] Resolving dependencies............
Package polymer_ui_elements requires SDK version >=0.8.5+1 <0.8.6 but the current SDK is 1.0.0+3.r30188.

*\* Warning: Application may fail to run since packages did not get installed.Try running pub get again. **

**Comment by zoechi** [comment]
Hi a4snet,

I'm excited to hear that you already use (or try to use) polymer_ui_element.

We already upgraded the polymer_elements (Github repository only).

We are going to publish an updated package this week to make polymer_elements available.
Don't expect the polymer_ui_elements to be working properly yet though, as we are still working 
to reflect the latest changes in Polymer.dart and integrate the latest changes from the JavaScript polymer-elements. 

A quick fix is to reference the Github repository directly with a dependency like

```
   polymer_ui_elements:
     git: git@github.com:ErikGrimes/polymer_ui_elements.git
```

To be on the safe side you can clone the repository to your local disk with
git clone git@github.com:ErikGrimes/polymer_ui_elements.git

and use a path dependency

```
   polymer_ui_elements:
     path: ../polymer_ui_elements
```

(if you project and the polymer_ui_elements have the same parent directory)

Hope this helps.
Günter

**Comment by a4snet** [comment]
Hallo Günter,

Thanks for the fast answer. Actually I’m working on a new project. 
We’ll use Dartlang and Polymer with all components that are in Production or pre Production. 

When ever I found some Issues I’ll be proud to inform you.

Thanks for this good work.

Frank

Am 09.12.2013 um 09:46 schrieb Günter Zöchbauer notifications@github.com:

**Comment by zoechi** [comment]
Hi Frank,

we just published a new release to pub.dartlang.org.
You may switch back to hosted dependencies if you like.

How is your progress. Do the elements work for your?

Günter

**Comment by a4snet** [comment]
Thanks for the Information.
I could import this Package without Problems.

I’ve tried to use the Field. But it seems that there are
some problems.

Perhaps because the Original polymer-ui-field use a Theme ?

Am 17.12.2013 um 13:48 schrieb Günter Zöchbauer notifications@github.com:

**Comment by a4snet** [comment]
Hallo,

I try to use sidebar_menu and the

Pointer is working nor fine.

When I Try to resize the Browser
Windows I got fallowing error

The error is in dart.js.

Happy New Year

Frank

**Comment by zoechi** [comment]
Hi a4snet,

it seems that I somehow overlooked your comment on polymer_ui_field - sorry for that.
Do you still have issues with polymer_ui_field?

In your message from yesterday you reference an error message but your message doesn't contain one.
Can you please edit your message so that the error is included.
Maybe some characters misinterpreded by the Github markup interpreter intervened.

We didn't yet succeed building the polymer_ui_examples to JavaScript because the `pub build` fails with `out of memory` error because of the many entry pages.
We could split the example pages to different packages but that doesn't help for deployment
So we thought spending our time porting more elements and hope the bug will be solved soon is more efficient instead of coping with expensive workarounds.

Happy New Year

Günter

**Comment by dannymk** [comment]
Package polymer_ui_elements requires SDK version >=0.8.5+1 <0.8.6 but the current SDK is 1.1.3.
Modifying "pubspec.yaml" to:

```
polymer_ui_elements:
    git: git@github.com:ErikGrimes/polymer_ui_elements.git    
```

produces the error:
Pub get failed, [1] Resolving dependencies.......................................
Package polymer_elements has no versions that match >=0.1.1 <0.2.0 derived from:
- AdminInterface depends on version any
- polymer_ui_elements depends on version >=0.1.1 <0.2.0

The important parts of my pubspec.yaml file are:
...

```
dependencies:
     browser: any
     polymer: 0.9.5
     polymer_elements: any
     polymer_ui_elements:
         git: git@github.com:ErikGrimes/polymer_ui_elements.git
     widget: any
```

**Comment by zoechi** [comment]
dannymk
The project got a bit stale lately. But I got 'pub build' working yesterday (no more out of memory build failures). 
I'll take a look.

**Comment by zoechi** [comment]
@dannymk 
Should be solved. I published a new release.

**Comment by dannymk** [comment]
Darnit, I missed this update.  I still have the same issue:

Pub get failed, [1] Resolving dependencies................................................................................
Package polymer_elements has no versions that match >=0.1.1 <0.2.0 derived from:
- AdminInterface depends on version any
- polymer_ui_elements depends on version >=0.1.1 <0.2.0

*\* Warning: Application may fail to run since packages did not get installed.Try running pub get again. 
**

I updated my pubspec... to:
...
dependencies:
  browser: any
  polymer: any
  polymer_elements: 
    git: git@github.com:ErikGrimes/polymer_elements.git
  polymer_ui_elements:
    git: git@github.com:ErikGrimes/polymer_ui_elements.git
  widget: any
...

With this change I get:
Pub get failed, [1] Resolving dependencies.......................
Incompatible dependencies on polymer_ui_elements:
- AdminInterface depends on it from source git
- polymer_elements depends on it from source hosted

*\* Warning: Application may fail to run since packages did not get installed.Try running pub get again. **

If I change to hosted repository:
...
dependencies:
  browser: any
  polymer: any
  polymer_elements: any
  polymer_ui_elements: any
  widget: any
...

I get the following error:
--- 3:40:40 PM Auto running pub get ... ---
Pub get failed, [1] Resolving dependencies...........................................................................................................................................................................................................
Package polymer_ui_elements requires SDK version >=0.8.5+1 <0.8.6 but the current SDK is 1.2.0.

**Comment by zoechi** [comment]
You should use `pub upgrade` instead of `pub get`. `pub get` tries to stick with the current versions and just tries to resolve conflicts. `pub upgrade` tries to find the most recent stable version that fulfills all version constraints.

**Comment by dannymk** [comment]
Thank you, resolved it by both upgrading to the latest dev sdk and polymer libraries.
I will also use pub upgrade from now on.
